services:
  admin:
    build:
      context: ..
      dockerfile: admin/Dockerfile
    ports:
      - "8081:8081"
    environment:
      ADMIN_PORT: 8081
    volumes:
      - admin-data:/data/configs

  player:
    build:
      context: ..
      dockerfile: player/Dockerfile
    ports:
      - "7070:7070"
    environment:
      PLAYER_PORT: 7070
    depends_on:
      - admin

volumes:
  admin-data:
